import { Heroe } from './heroe';
export const HEROES: Heroe[] = [
  {
    nombre: 'Izuku Midoriya',
    alias: 'Deku',
    bio: 'One For All: Le permite acumular poder y transferirlo a otros.',
    img: '../../../assets/images/deku_1.jpg',
    aparicion: 'Volumen 8 (Julio 2016)',
    ocupacion: 'Héroe estudiante',
  },
  {
    nombre: 'Katsuki Bakugo',
    alias: 'Dynamight',
    bio: 'Explosión: Le permite generar explosiones con las palmas de sus manos.',
    img: '../../../assets/images/bakugo_1.jpg',
    aparicion: 'Volumen 2 (Junio 2014)',
    ocupacion: 'Héroe estudiante',
  },
  {
    nombre: 'Shoto Todoroki',
    alias: 'Shoto',
    bio: 'Mitad y Mitad: Le permite controlar fuego y hielo.',
    img: '../../../assets/images/soto_1.jpg',
    aparicion: 'Volumen 2 (Junio 2014)',
    ocupacion: 'Héroe estudiante',
  },
  {
    nombre: 'Aizawa Shōta',
    alias: 'Eraser Head',
    bio: 'Ojo de Halcón: Le permite anular los Quirks de otros con la mirada.',
    img: '../../../assets/images/eraser_1.jpg',
    aparicion: 'Volumen 3 (Agosto 2014)',
    ocupacion: 'Héroe profesional y profesor',
  },
  {
    nombre: 'Kaina Tsutsumi',
    alias: 'Lady Nagant',
    bio: 'Rifle de francotirador: Le permite disparar balas con diferentes efectos.',
    img: '../../../assets/images/nagant_1.jpg',
    aparicion: 'Volumen 32 (Noviembre 2021)',
    ocupacion: 'Villana, EX-Héroe profesional',
  },
  {
    nombre: 'Keigo Takami',
    alias: 'Hawks',
    bio: 'Alas de Halcón: Le permite volar a gran velocidad y usar sus plumas como proyectiles.',
    img: '../../../assets/images/hawks_1.jpg',
    aparicion: 'Volumen 2 (Junio 2014)',
    ocupacion: 'Héroe profesional',
  },
  {
    nombre: 'Togata Mirio',
    alias: 'Lemillion',
    bio: 'Permeabilidad: Le permite atravesar cualquier objeto sólido.',
    img: '../../../assets/images/mirio_1.jpg',
    aparicion: 'Volumen 15 (Noviembre 2017)',
    ocupacion: 'Héroe profesional',
  },
  {
    nombre: 'Nejire Hado',
    alias: 'Nejire-chan',
    bio: 'Ola de Energía: Le permite generar y controlar ondas de energía.',
    img: '../../../assets/images/nejire_1.jpg',
    aparicion: 'Volumen 10 (Junio 2016)',
    ocupacion: 'Héroe estudiante',
  },
  {
    nombre: 'Tamaki Amajiki',
    alias: 'Suneater',
    bio: 'Manifestación: Le permite manifestar las propiedades de cualquier cosa que coma.',
    img: '../../../assets/images/tamaki_1.jpg',
    aparicion: 'Volumen 8 (Julio 2016)',
    ocupacion: 'Héroe estudiante',
  },
  {
    nombre: 'Kurose Anan',
    alias: 'Thirteen',
    bio: 'Black Hole: Le permite absorber cualquier cosa y enviarla a otra dimensión.',
    img: '../../../assets/images/kurose_1.jpg',
    aparicion: 'Volumen 1 (Julio 2014)',
    ocupacion: 'Héroe profesional',
  },
  {
    nombre: 'Rumi Usagiyama',
    alias: 'Bunny Hero: Miruko',
    bio: 'Patas de Conejo: Le da fuerza y velocidad sobrehumanas en sus piernas.',
    img: '../../../assets/images/mirko_1.jpg',
    aparicion: 'Volumen 15 (Noviembre 2017)',
    ocupacion: 'Héroe profesional',
  },
  {
    nombre: 'Hizashi Yamada',
    alias: 'Present Mic',
    bio: 'Voice: Le permite amplificar su voz y usarla para diversos fines.',
    img: '../../../assets/images/present_1.jpg',
    aparicion: 'Volumen 1 (Julio 2014)',
    ocupacion: 'Héroe profesional y profesor',
  },
];
